# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DP <- function(parameters, M, N_truncated, N_sample, CDP = TRUE) {
    .Call(`_SBMTrees_DP`, parameters, M, N_truncated, N_sample, CDP)
}

update_DP_normal <- function(X, tau, L = -1, U = 2) {
    .Call(`_SBMTrees_update_DP_normal`, X, tau, L, U)
}

DP_sampler <- function(N, parameters) {
    .Call(`_SBMTrees_DP_sampler`, N, parameters)
}

bart_train <- function(X, Y, nburn = 100L, npost = 1000L, verbose = TRUE) {
    .Call(`_SBMTrees_bart_train`, X, Y, nburn, npost, verbose)
}

sequential_imputation_cpp <- function(X, Y, type, Z, subject_id, R, binary_outcome = FALSE, nburn = 0L, npost = 3L, skip = 1L, verbose = TRUE, CDP_residual = FALSE, CDP_re = FALSE, seed = NULL, tol = 1e-20, ncores = 0L, ntrees = 200L, fit_loss = FALSE, resample = 0L, pi_CDP = 0.99) {
    .Call(`_SBMTrees_sequential_imputation_cpp`, X, Y, type, Z, subject_id, R, binary_outcome, nburn, npost, skip, verbose, CDP_residual, CDP_re, seed, tol, ncores, ntrees, fit_loss, resample, pi_CDP)
}

BMTrees_mcmc <- function(X, Y, Z, subject_id, obs_ind, binary = FALSE, nburn = 0L, npost = 3L, verbose = TRUE, CDP_residual = FALSE, CDP_re = FALSE, seed = NULL, tol = 1e-40, ntrees = 200L, resample = 0L, pi_CDP = 0.99) {
    .Call(`_SBMTrees_BMTrees_mcmc`, X, Y, Z, subject_id, obs_ind, binary, nburn, npost, verbose, CDP_residual, CDP_re, seed, tol, ntrees, resample, pi_CDP)
}

update_Covariance <- function(B, Mu, inverse_wishart_matrix, df, N_subject) {
    .Call(`_SBMTrees_update_Covariance`, B, Mu, inverse_wishart_matrix, df, N_subject)
}

